project_id = "ubkcdrdetqjjynxtgdam"

[functions.explain-topic]
verify_jwt = true

[functions.analyze-student-risk]
verify_jwt = true

[functions.generate-parent-summary]
verify_jwt = true

[functions.generate-question-paper]
verify_jwt = true

[functions.generate-school-report]
verify_jwt = true
